<?xml version="1.0"?>
<package format="2">
  <name>ackermann_vehicle_navigation</name>
  <version>0.1.5</version>
  <description>
    Navigation helpers and command conversion nodes for ackermann_vehicle.
  </description>

  <maintainer email="hdh7485@kaist.ac.kr">Donghee Han</maintainer>
  <license>Apache 2.0</license>
  <url type="bugtracker">https://github.com/hdh7485/ackermann_vehicle/issues</url>
  <url type="repository">https://github.com/hdh7485/ackermann_vehicle.git</url>
  <author email="jim.rothrock@wunderkammerlab.com">Jim Rothrock</author>

  <buildtool_depend>catkin</buildtool_depend>

  <build_depend>ackermann_msgs</build_depend>
  <build_depend>gazebo_msgs</build_depend>
  <build_depend>geometry_msgs</build_depend>
  <build_depend>nav_msgs</build_depend>
  <build_depend>rospy</build_depend>
  <build_depend>std_msgs</build_depend>
  <build_depend>tf</build_depend>
  <build_depend>tf2_ros</build_depend>
  <build_export_depend>ackermann_msgs</build_export_depend>
  <build_export_depend>gazebo_msgs</build_export_depend>
  <build_export_depend>geometry_msgs</build_export_depend>
  <build_export_depend>nav_msgs</build_export_depend>
  <build_export_depend>rospy</build_export_depend>
  <build_export_depend>std_msgs</build_export_depend>
  <build_export_depend>tf</build_export_depend>
  <build_export_depend>tf2_ros</build_export_depend>
  <exec_depend>ackermann_msgs</exec_depend>
  <exec_depend>gazebo_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>nav_msgs</exec_depend>
  <exec_depend>rospy</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>tf</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>tf_conversions</exec_depend>
  <exec_depend>python3-numpy</exec_depend>
  <exec_depend>python3-rospkg</exec_depend>

  <export>
  </export>
</package>
